---

- name: "update packages"
  become: true
  apt: 
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt: 
    upgrade: yes

- name: "add nodejs from nodesource."
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  async: 2100
  poll: 0

- name: "install nodejs 13"
  become: true
  apt:
    name: ["nodejs"]
    state: "latest"
    update_cache: yes

- name: "install pm2 globally"
  npm:
    name: "pm2"
    global: yes