---
- name: "add nodejs from nodesource."
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: "install nodejs 14"
  become: true
  apt:
    name: ["nodejs"]
    state: "latest"
    update_cache: yes

- name: "install pm2 globally"
  npm:
    name: "pm2"
    global: yes